on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Run tests
      run: hatch run tests:run
      env:
        KEY: ${{ secrets.KEY }}
